"""empty message

Revision ID: 93bb75e83e4c
Revises: f08cf2b500ee
Create Date: 2026-03-22 18:21:47.246170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bb75e83e4c'
down_revision: Union[str, Sequence[str], None] = 'f08cf2b500ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes needed - constraints are defined in models
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes to revert
    # ### end Alembic commands ###
